#!/usr/bin/env bash
# Loop through numbers from 1 to 100
for i in {1..100}; do
    # Check if the number is divisible by both 3 and 5
    if (( i % 3 == 0 && i % 5 == 0 )); then
        echo "FizzBuzz"
    # Check if the number is divisible by 3
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    # Check if the number is divisible by 5
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    # Otherwise, just print the number
    else
        echo "$i"
    fi
done

